author: MDCollins
database: false
description: Converts donated values (as entered by an admin) to the in-game currency.
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: com.blockmovers.plugins.donationvault.Donationvault
name: DonationVault
startup: postworld
url: http://blockmovers.com/
version: '${version}'
commands:
  donationvault:
    usage: /<command> [player] [amount]
    aliases: dv
permissions:
  donationvault.admin:
    default: false
    description: allows players add funds to another players balance
    children:
      donationvault.check: true
  donationvault.check:
    default: false
    description: allows players add funds to another players balance